### ISSUE TITLE
Cant get pack to work?

### ISSUE THREAD

**Issue by MrSpectre201** [Elemend/Builders-Wand#1]
Hi,
I downloaded the pack so I could work on a guardian farm in 1.13 with some extensive same-block building, but I cant get it to work. I got the resourcepack and the datapack in the proper places, so im not sure what the issue is. I tried using 1.13, 1.13.1, and 1.13.2. Also, I tried unzipping the folder "builders_wand", leaving it zipped, having both, and leaving the master folder in the datapacks folder. Im not sure if im doing something in-game wrong or if its a problem with the files though. The wand just wouldn't craft, and I don't even know what the recipe is because the read.me is vague.
Can I have some help?

**Comment by Elemend** [comment]
I'm hopeful the read.me is clearer now.  I hope that helps.
