### ISSUE TITLE
Chat spam even when pack is disabled

### ISSUE THREAD

**Issue by maicol07** [Elemend/Builders-Wand#11]
See here: MinecraftPhi/MinecraftPhi-modules#12

**Comment by Elemend** [comment]
That's an Issue with Spigot If I understood that right? What could I possibly do about this?

**Comment by maicol07** [comment]
I don't know... Is Phi important for the pack?

**Comment by Elemend** [comment]
it is

**Comment by Elemend** [comment]
Does this Issue still occur with the latest version?

**Comment by maicol07** [comment]
@Elemend I have this issue with the December release for 1.16.2... although your fix for command timings helped. The two commands described in the other issue don't work... maybe running the command at the maximum delay? Or maybe run manually if they do not have any issues
