### ISSUE TITLE
World loading stuck on 100%

### ISSUE THREAD

**Issue by poots6** [Elemend/Builders-Wand#12]
Basically this [problem](https://github.com/MinecraftPhi/MinecraftPhi-modules/issues/13), except the Phi files didn't load when I did the /reload command. The mod did work when I first installed it, but now, the world doesn't even load after waiting 30 min.

**Comment by poots6** [comment]
Oh wait! I think I fixed it? Could be temporary.

1. remove **phi** files to another location like Desktop
2. Load Minecraft and world and pause
3. Put back **phi** files in original location (**data** folder)
4. Go back to world, type **/reload**, and it should work

**Comment by Elemend** [comment]
I think the latest Version should get rid of this Issue, hopefully

**Comment by jengendler** [comment]
I'm experiencing the exact same issue on 1.16.1. Is this the latest version you're talking about? Removing/reloading the file seems to work as @poots6 mentioned.

**Comment by Elemend** [comment]
What I mean with latest Version is the most recent zip file:
https://github.com/Elemend/Builders-Wand/blob/master/1.16/builders_wand_1.16.zip
If you want to be absolutely sure to not have Issues again, install that, run the uninstall function once in chat and then /reload.
