### ISSUE TITLE
World is lagging so much after deinstalling

### ISSUE THREAD

**Issue by JorLord123** [Elemend/Builders-Wand#13]
We installed the pack bc we thaught we could built easier in creative. After a couple of minutes of testing the world was lagging a lot. So we decided to run the command /function bw:uninstall_bw and to delete the datapack. But even after a complete server restart the server was lagging. 
Today we discovered that my mate did not used the command /function bw:uninstall_bw and he still had the tags of the datapack.
I thought that this command would work for everyone at the server. 
I just removed the tags but any ideas what we can do, to stop the lags?

Do we need to install the data pack again and than run the command?

**Comment by JorLord123** [comment]
![Minecraft bug](https://user-images.githubusercontent.com/68852797/88546466-b4d8f300-d01c-11ea-999c-209976c5f538.PNG)

**Comment by JorLord123** [comment]
guess I found something and not quite sure what to do

**Comment by Elemend** [comment]
mhm, try using the latest Version. Maybe that fixed it?

**Comment by Elemend** [comment]
well, using the latest Version and running the uninstall function once through chat and then reloading should work

**Comment by JorLord123** [comment]
ok thanks it worked
