### ISSUE TITLE
Very high tps lag with this datapack

### ISSUE THREAD

**Issue by Notme2222** [Elemend/Builders-Wand#14]
![Pre Activation](https://user-images.githubusercontent.com/51098482/94862661-e85e4200-03fe-11eb-85f2-f3ab374058fd.png)
![Post Activation](https://user-images.githubusercontent.com/51098482/94862665-e8f6d880-03fe-11eb-971f-bbf06b0acf3d.png)
The TPS is much much lower after I forceload the chunk in the overworld. 
I have tried completely reinstalling the datapack, but it still causes a significant amount of lag. I've been able to reproduce it once, however I'm not sure what the trigger is, but I think it might be leaving a world open for a long time.
The only solution to this seems to be to completely uninstall the datapack and delete the phi chunks then readd the datapack and reload

**Comment by Notme2222** [comment]
The images are included because the tps is shown on the top left corner btw

**Comment by Elemend** [comment]
Are you on minecraft version 1.16 and you use the latest version of this data pack? Do you have Phi as a seperate data pack installed? 

As of the Version uploaded 2 months ago these messages do not appear anymore. The data pack doesn't have a direct dependancy on Phi anymore. Only the parts that the builder's wand data pack directly uses are included. Everything else from Phi was removed.

I suggest removing Phi if you don't need it for other data packs. And maybe the latest version fixes this?

**Comment by Notme2222** [comment]
I am on 1.16.2
I am using the latest version and I do not have Phi as a separate datapack
I have installed it on another other world and it seems to be doing fine, but the problem still persists on my creative world for some reason, although I have had troubles reproducing it consistently, especially as it seems to be time in game based. 
I am curious though if anything requires solid blocks because my creative worlds are just 5 layers of white stained glass and perhaps that could be causing the issue?

**Comment by Elemend** [comment]
So did anything change? I made a new experimental release which I don't expect to fix this Issue, but you never know...
