### ISSUE TITLE
Switching it to off hand is deleting the item

### ISSUE THREAD

**Issue by Notme2222** [Elemend/Builders-Wand#2]

**Comment by Elemend** [comment]
Did you install Phi correctly? This datapack has a dependency on that, and if it's missing, that happens.

**Comment by Notme2222** [comment]
Phi seems to be installed correctly. I got the message on reload. I don’t know if all the modules worked though.

**Comment by Elemend** [comment]
This is how my Phi installation looks like on my testworld, maybe that helps?

![Phi](https://user-images.githubusercontent.com/41597650/58494553-a1f73400-8175-11e9-8cdc-8c926e12ce36.png)

**Comment by Notme2222** [comment]
This is over a year late but yes, my phi installation was screwed and that was causing the problem
