### ISSUE TITLE
Add an option to choose  direction based on player facing

### ISSUE THREAD

**Issue by MarcusElg** [Elemend/Builders-Wand#3]
Would be much more convenient imo and would be super easy to implement

**Comment by MarcusElg** [comment]
Any update?

**Comment by Elemend** [comment]
I am actively working on this datapack. This Issue here is on my agenda, but I am also planning on extending blockplacing to allow the player to stack flat areas on top of each other, meaning in 2 Dimensions. And then everything will be released in 1 big update.

**Comment by MarcusElg** [comment]
Glad you are working on it!

**Comment by Elemend** [comment]
Now that I added commands that adjust the block placing to player rotaion I consider this Issue solved.

**Comment by MarcusElg** [comment]
Thank you very much!
