### ISSUE TITLE
Ability to place blocks with item entities in the way?

### ISSUE THREAD

**Issue by RagingLink** [Elemend/Builders-Wand#4]
It'd be really nice to be able to use the builder's wand if there are items in the way. Or perhaps tell me how to disable the entity detection myself?

**Comment by Elemend** [comment]
thanks for bringing this up, as it really makes sense to ignore items. You can find the entity detection if you search the pack for lines which contain `@e[dx=0,limit=1]`
you can change it to `@e[type=!item,dx=0,limit=1]`
I will edit this into the pack as well, but I'm still working on other things in the pack too, so not to be released just yet.

**Comment by RagingLink** [comment]
Yeah that worked! And really no problem o/
