### ISSUE TITLE
Free items on login?!

### ISSUE THREAD

**Issue by Techokami** [Elemend/Builders-Wand#5]
So for some reason, every time I log into my server that has this data pack installed to, I get all 4 kinds of wands for free added to my inventory. Why??

**Comment by Elemend** [comment]
I have no Idea. What contents does the shulker box at -30000000 0 1602 have?

**Comment by Techokami** [comment]
After checking the region file with NBTExplorer, absolutely nothing. It doesn't even have the tag for holding items!
![image](https://user-images.githubusercontent.com/1530728/71766852-98376b00-2ed2-11ea-863e-088d8374b4d8.png)

**Comment by Elemend** [comment]
Ok, that shows it's not the shulker box being the problem. I thought about it some more, and the only place where there is a "/give" command in this pack is in the reward functions for the advancements which keep track of the player wanting to craft the wands.
Somehow, these activate for you on reload. I don't know how that is possible. These advancements can only activate if the player takes the item from the crafting table. Is there something that grants all advancements on reload?

**Comment by Techokami** [comment]
Okay I figured it out. Quark, one of the mods I'm using, has the ability to just give you all the crafting recipes (because I've been playing Minecraft since alpha and I don't need to be spoon-fed recipes), and when I disabled that on the client and server side, it's not giving me free wands anymore.
