### ISSUE TITLE
phi chunk in the overworld won't force load

### ISSUE THREAD

**Issue by systemshaper** [Elemend/Builders-Wand#7]
Hi, thanks for taking this on, there is a distinct lack of building tools for the latest versions that I've seen.

Unfortunately, when I startup a world and get the initial prompts to chunk load, the prompt for the overworld just keeps repeating, clicking on it just results in "No chunks were marked for force loading". Presumably as a result, while I can craft the wands and see the particles, right clicking does not place any blocks.

I'm on forge 31.1.14 for minecraft 1.15.2. I've got ~30 mods and a fresh world.
I switched to a pure vanilla world and the chunk loading prompts were successful, so apparently this is a conflict of some sort, and not any innate issue with your datapack. But I was just wondering if perhaps you had any suggestions that might help avoid conflicts?

![image](https://user-images.githubusercontent.com/59181708/75100596-79ca2380-5595-11ea-99d1-3473028c2499.png)

**Comment by Elemend** [comment]
Interesting that the Overworld would be the only place where there is an Issue. Did you try to place blocks in the Nether or End too? I kind of anticipate it not working there as well. 

As for what mod interferes, maybe "ChunkNoGoByeBye" can't have any forceloaded chunks besides the ones it would provide itself? Other than that, I remember Optifine has a setting which would remove loaded chunks to save on memory, which you don't have... but maybe some other mod has a similar method or setting to save used memory? 

To figure out what mod exactly you propably would need to uninstall one after the other until it works? But if you're playing modded already, why not install the "Better Builder's Wand Mod" anyway? Why use a datapack which is lackluster when compared directly to the mod?

**Comment by systemshaper** [comment]
Yes, it didn't work in any dimension. I tested mods individually and "immersive portals" is the mod in conflict with this datapack. So I guess for now I'll have to choose between easier building or better portals. I would install a builders wand mod if any existed for 1.15, but so far I haven't found any. Better Builder's Wand as far as I can see is still back on 1.12.2.

Thanks for your help though.
