### ISSUE TITLE
Some doubt

### ISSUE THREAD

**Issue by EnterFor** [Elemend/Builders-Wand#8]
Hi，I'm a Chinese gamer and I've been looking for a building mod that supports 1.15 and I stumbled on this.

I have a few questions can you answer?

1. Do you support server usage?

2. Why wasn't it published to curseforge so more people could know about it?

3. Wait for supplements

**Comment by Elemend** [comment]
1. As far as I'm aware it works on Servers.
2. I don't know.
3. ?

**Comment by EnterFor** [comment]
Thanks
